* ext/oci8/oci8.c: prevent GC on failed-logon connections from freeing     alive connections when the service context handle addresses are     accidentally same. * ext/oci8/ocidatetime.c: raise "OCIError: ORA-01805: possible error in     date/time operation" when Oracle 11gR2's client and server timezone versions     are not same instead of raising a exception "undefined method `*' for     nil:NilClass." This is a temporary fix.     See: http://rubyforge.org/forum/forum.php?thread_id=49102&forum_id=1078
git-svn-id: svn+ssh://rubyforge.org/var/svn/ruby-oci8/branches/ruby-oci8-2.0@426 f081da96-e817-0410-9439-ba585a54bbf1